name: etcd

stemcells:
- alias: default
  os: ubuntu-xenial
  version: "97.34"

releases:
- name: cfcr-etcd
  version: 1.4.1
- name: bpm
#  sha1: 5a03b988c725c6b5a1aed247c8c23c2bff9d421b
#  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.4.0
  version: 0.6.0
- name: bosh-dns
  version: 1.10.0

instance_groups:
- name: etcd
  # CHANGEME Use availibility zones in your director tile
  azs: [az-1,az-2,az-3]
  instances: 3
  persistent_disk_type: 10240
  vm_type: medium
  stemcell: default
  networks:
  # CHANGEME Use the networks configured in the director tile
  - name: default
  jobs:
  - name: etcd
    release: cfcr-etcd
    provides:
      etcd: {as: etcd}
  - name: bpm
    release: bpm

- name: acceptance
  # CHANGEME
  azs: [az-1]
  instances: 1
  lifecycle: errand
  vm_type: small
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: acceptance-tests
    release: cfcr-etcd
    consumes:
      etcd: {from: etcd}

update:
  serial: true
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

variables:
- name: /dns_healthcheck_tls_ca
  opsname: global_dns_healthcheck_tls_ca
  type: certificate
  options:
    is_ca: true
    common_name: dns-healthcheck-tls-ca

- name: /dns_healthcheck_server_tls
  opsname: global_dns_healthcheck_server_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - server_auth

- name: /dns_healthcheck_client_tls
  opsname: global_dns_healthcheck_client_tls
  type: certificate
  options:
    ca: /dns_healthcheck_tls_ca
    common_name: health.bosh-dns
    extended_key_usage:
    - client_auth

features:
  converge_variables: true
  use_dns_addresses: true
